### ISSUE TITLE
Note (Bower) ngFileReader is compatible with Angular 1.5.0

### ISSUE THREAD

**Issue by grrseguin** [SparrowJang/ngFileReader#3]
Hello,

I'm coming to upgrade my project with Angular 1.5.0 and i use also the last version of `ngFileReader` (0.0.6).

For me, `ngFileReader` work fine !

For testing :
1. Go to [this page](https://anagene.reseau-canope.fr/#/teacher/sequence/import) ;
2. Click on 'Essayez gratuitement' button ;
3. drop [this file](http://acces.ens-lyon.fr/evolution/logiciels/anagene/sequences/igg-4chaines-eu.edi) on the 'FICHIER EDI' block ;
4. Finally, click on 'Importer' button.

I think that you can set the dependency of Angular to `~1.5.0`.

**Comment by SparrowJang** [comment]
release 0.0.7 version
